services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iot_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - iot_network

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/code
    networks:
      - iot_network

  # celery_worker:
  #   build: .
  #   command: celery -A app.tasks.celery worker --loglevel=info
  #   depends_on:
  #     - redis
  #     - postgres
  #   volumes:
  #     - .:/code

  # mosquitto:
  #   image: eclipse-mosquitto
  #   ports:
  #     - "1883:1883"
  #   volumes:
  #     - ./mosquitto.conf:/mosquitto/config/mosquitto.conf


volumes:
  postgres_data:

networks:
  iot_network: